from __future__ import print_function, absolute_import, division 
ACCELERATION_X = "ACCELERATION_X"
ACCELERATION_Y = "ACCELERATION_Y"
ACCELERATION = ["ACCELERATION",ACCELERATION_X,ACCELERATION_Y]
DISPLACEMENT_X = "DISPLACEMENT_X"
DISPLACEMENT_Y = "DISPLACEMENT_Y"
DISPLACEMENT = ["DISPLACEMENT",DISPLACEMENT_X, DISPLACEMENT_Y]
VELOCITY_X = "VELOCITY_X"
VELOCITY_Y = "VELOCITY_Y"
VELOCITY = ["VELOCITY",VELOCITY_X,VELOCITY_Y]
YOUNG_MODULUS = "YOUNG_MODULUS"
POISSON_RATIO = "POISSON_RATIO"
DENSITY = "DENSITY"
VISCOSITY = "VISCOSITY"
TIME = "TIME"
DELTA_TIME = "DELTA_TIME"
TEMPERATURE = "TEMPERATURE"
CONDUCTIVITY = "CONDUCTIVITY"
VOLUME_HEAT_SOURCE = "VOLUME_HEAT_SOURCE"
PRESSURE = "PRESSURE"
BODY_FORCE_X ="BODY_FORCE_X"
BODY_FORCE_Y = "BODY_FORCE_Y"
BDF_COEFFICIENTS = "BDF_COEFFICIENTS"
BOSSAK_COEFFICIENTS = "BOSSAK_COEFFICIENTS"
IS_LAGRANGIAN = "IS_LAGRANGIAN"
IS_BOUNDARY   = "IS_BOUNDARY"
IS_STRUCTURE  = "IS_STRUCTURE"
EXTERNAL_FORCE_X = "EXTERNAL_FORCE_X"
EXTERNAL_FORCE_Y = "EXTERNAL_FORCE_Y"
# Dennis begin
EXTERNAL_MOMENT_MZ = "EXTERNAL_MOMENT_MZ"
# Dennis end
EXTERNAL_UNIT_DENSITY = "EXTERNAL_UNIT_DENSITY"
FACE_HEAT_FLUX = "FACE_HEAT_FLUX"
OUTLET_PRESSURE = "OUTLET_PRESSURE"
NORMAL_X = "NORMAL_X"
NORMAL_Y = "NORMAL_Y"
NORMAL = ["NORMAL",NORMAL_X, NORMAL_Y]
